services:
  app-client:
    image: app-client:0.2
    ports:
      - 3000:3000

  app-server:
    image: app-server:0.6
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1251
      - POSTGRES_DB=calc_app
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
